# Parsing Code using Llama Parse v2.5
UCB MFE FT ID GROUP - RL \\
In order to run this code, you need api from llama Cloud: \\
you would need LLAMA_CLOUD_API_KEY @ https://cloud.llamaindex.ai/project/bf1f404e-ee25-4695-a2e6-eb5519ac661a \\
Documentation: https://docs.cloud.llamaindex.ai/llamaparse/getting_started/python

For the data porting, we choose to use openai to handel all the information and data cleaning and organisation, so that it looks exactly like the excel format which was provided by Luis.

In [ ]:
%pip install llama-parse

Collecting llama-parse
  Downloading llama_parse-0.6.4.post1-py3-none-any.whl.metadata (6.9 kB)
Collecting llama-cloud-services>=0.6.4 (from llama-parse)
  Downloading llama_cloud_services-0.6.9-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: click<9.0.0,>=8.1.7 in /usr/local/lib/python3.11/dist-packages (from llama-cloud-services>=0.6.4->llama-parse) (8.1.8)
Collecting llama-cloud<0.2.0,>=0.1.17 (from llama-cloud-services>=0.6.4->llama-parse)
  Downloading llama_cloud-0.1.17-py3-none-any.whl.metadata (902 bytes)
Collecting llama-index-core>=0.11.0 (from llama-cloud-services>=0.6.4->llama-parse)
  Downloading llama_index_core-0.12.28-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: platformdirs<5.0.0,>=4.3.7 in /usr/local/lib/python3.11/dist-packages (from llama-cloud-services>=0.6.4->llama-parse) (4.3.7)
Requirement already satisfied: pydantic!=2.10 in /usr/local/lib/python3.11/dist-packages (from llama-cloud-services>=0.6.4->llama-parse) (2.11.1)
Collecting python-dotenv<2.0.0,>=1.0.1 (from llama-cloud-services>=0.6.4->llama-parse)
  Downloading python_dotenv-1.1.0-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: certifi>=2024.7.4 in /usr/local/lib/python3.11/dist-packages (from llama-cloud<0.2.0,>=0.1.17->llama-cloud-services>=0.6.4->llama-parse) (2025.1.31)
Requirement already satisfied: httpx>=0.20.0 in /usr/local/lib/python3.11/dist-packages (from llama-cloud<0.2.0,>=0.1.17->llama-cloud-services>=0.6.4->llama-parse) (0.28.1)
Requirement already satisfied: PyYAML>=6.0.1 in /usr/local/lib/python3.11/dist-packages (from llama-index-core>=0.11.0->llama-cloud-services>=0.6.4->llama-parse) (6.0.2)
Requirement already satisfied: SQLAlchemy>=1.4.49 in /usr/local/lib/python3.11/dist-packages (from SQLAlchemy[asyncio]>=1.4.49->llama-index-core>=0.11.0->llama-cloud-services>=0.6.4->llama-parse) (2.0.40)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.6 in /usr/local/lib/python3.11/dist-packages (from llama-index-core>=0.11.0->llama-cloud-services>=0.6.4->llama-parse) (3.11.15)
Collecting banks<3.0.0,>=2.0.0 (from llama-index-core>=0.11.0->llama-cloud-services>=0.6.4->llama-parse)
  Downloading banks-2.1.1-py3-none-any.whl.metadata (11 kB)
Collecting dataclasses-json (from llama-index-core>=0.11.0->llama-cloud-services>=0.6.4->llama-parse)
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: deprecated>=1.2.9.3 in /usr/local/lib/python3.11/dist-packages (from llama-index-core>=0.11.0->llama-cloud-services>=0.6.4->llama-parse) (1.2.18)
Collecting dirtyjson<2.0.0,>=1.0.8 (from llama-index-core>=0.11.0->llama-cloud-services>=0.6.4->llama-parse)
  Downloading dirtyjson-1.0.8-py3-none-any.whl.metadata (11 kB)
Collecting filetype<2.0.0,>=1.2.0 (from llama-index-core>=0.11.0->llama-cloud-services>=0.6.4->llama-parse)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core>=0.11.0->llama-cloud-services>=0.6.4->llama-parse) (2025.3.2)
Requirement already satisfied: nest-asyncio<2.0.0,>=1.5.8 in /usr/local/lib/python3.11/dist-packages (from llama-index-core>=0.11.0->llama-cloud-services>=0.6.4->llama-parse) (1.6.0)
Requirement already satisfied: networkx>=3.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core>=0.11.0->llama-cloud-services>=0.6.4->llama-parse) (3.4.2)
Requirement already satisfied: nltk>3.8.1 in /usr/local/lib/python3.11/dist-packages (from llama-index-core>=0.11.0->llama-cloud-services>=0.6.4->llama-parse) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from llama-index-core>=0.11.0->llama-cloud-services>=0.6.4->llama-parse) (2.0.2)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core>=0.11.0->llama-cloud-services>=0.6.4->llama-parse) (11.1.0)
Requirement already satisfied: requests>=2.31.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core>=0.11.0->llama-cloud-services>=0.6.4->llama-parse) (2.32.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.2.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core>=0.11.0->llama-cloud-services>=0.6.4->llama-parse) (9.1.2)
Collecting tiktoken>=0.3.3 (from llama-index-core>=0.11.0->llama-cloud-services>=0.6.4->llama-parse)
  Downloading tiktoken-0.9.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: tqdm<5.0.0,>=4.66.1 in /usr/local/lib/python3.11/dist-packages (from llama-index-core>=0.11.0->llama-cloud-services>=0.6.4->llama-parse) (4.67.1)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core>=0.11.0->llama-cloud-services>=0.6.4->llama-parse) (4.13.0)
Collecting typing-inspect>=0.8.0 (from llama-index-core>=0.11.0->llama-cloud-services>=0.6.4->llama-parse)
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from llama-index-core>=0.11.0->llama-cloud-services>=0.6.4->llama-parse) (1.17.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic!=2.10->llama-cloud-services>=0.6.4->llama-parse) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.0 in /usr/local/lib/python3.11/dist-packages (from pydantic!=2.10->llama-cloud-services>=0.6.4->llama-parse) (2.33.0)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic!=2.10->llama-cloud-services>=0.6.4->llama-parse) (0.4.0)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core>=0.11.0->llama-cloud-services>=0.6.4->llama-parse) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core>=0.11.0->llama-cloud-services>=0.6.4->llama-parse) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core>=0.11.0->llama-cloud-services>=0.6.4->llama-parse) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core>=0.11.0->llama-cloud-services>=0.6.4->llama-parse) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core>=0.11.0->llama-cloud-services>=0.6.4->llama-parse) (6.3.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core>=0.11.0->llama-cloud-services>=0.6.4->llama-parse) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core>=0.11.0->llama-cloud-services>=0.6.4->llama-parse) (1.18.3)
Collecting griffe (from banks<3.0.0,>=2.0.0->llama-index-core>=0.11.0->llama-cloud-services>=0.6.4->llama-parse)
  Downloading griffe-1.7.2-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from banks<3.0.0,>=2.0.0->llama-index-core>=0.11.0->llama-cloud-services>=0.6.4->llama-parse) (3.1.6)
Requirement already satisfied: anyio in /usr/local/lib/python3.11/dist-packages (from httpx>=0.20.0->llama-cloud<0.2.0,>=0.1.17->llama-cloud-services>=0.6.4->llama-parse) (4.9.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx>=0.20.0->llama-cloud<0.2.0,>=0.1.17->llama-cloud-services>=0.6.4->llama-parse) (1.0.7)
Requirement already satisfied: idna in /usr/local/lib/python3.11/dist-packages (from httpx>=0.20.0->llama-cloud<0.2.0,>=0.1.17->llama-cloud-services>=0.6.4->llama-parse) (3.10)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx>=0.20.0->llama-cloud<0.2.0,>=0.1.17->llama-cloud-services>=0.6.4->llama-parse) (0.14.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from nltk>3.8.1->llama-index-core>=0.11.0->llama-cloud-services>=0.6.4->llama-parse) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.11/dist-packages (from nltk>3.8.1->llama-index-core>=0.11.0->llama-cloud-services>=0.6.4->llama-parse) (2024.11.6)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31.0->llama-index-core>=0.11.0->llama-cloud-services>=0.6.4->llama-parse) (3.4.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31.0->llama-index-core>=0.11.0->llama-cloud-services>=0.6.4->llama-parse) (2.3.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.11/dist-packages (from SQLAlchemy>=1.4.49->SQLAlchemy[asyncio]>=1.4.49->llama-index-core>=0.11.0->llama-cloud-services>=0.6.4->llama-parse) (3.1.1)
Collecting mypy-extensions>=0.3.0 (from typing-inspect>=0.8.0->llama-index-core>=0.11.0->llama-cloud-services>=0.6.4->llama-parse)
  Downloading mypy_extensions-1.0.0-py3-none-any.whl.metadata (1.1 kB)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json->llama-index-core>=0.11.0->llama-cloud-services>=0.6.4->llama-parse)
  Downloading marshmallow-3.26.1-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: packaging>=17.0 in /usr/local/lib/python3.11/dist-packages (from marshmallow<4.0.0,>=3.18.0->dataclasses-json->llama-index-core>=0.11.0->llama-cloud-services>=0.6.4->llama-parse) (24.2)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio->httpx>=0.20.0->llama-cloud<0.2.0,>=0.1.17->llama-cloud-services>=0.6.4->llama-parse) (1.3.1)
Collecting colorama>=0.4 (from griffe->banks<3.0.0,>=2.0.0->llama-index-core>=0.11.0->llama-cloud-services>=0.6.4->llama-parse)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->banks<3.0.0,>=2.0.0->llama-index-core>=0.11.0->llama-cloud-services>=0.6.4->llama-parse) (3.0.2)
Downloading llama_parse-0.6.4.post1-py3-none-any.whl (4.9 kB)
Downloading llama_cloud_services-0.6.9-py3-none-any.whl (29 kB)
Downloading llama_cloud-0.1.17-py3-none-any.whl (253 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 253.9/253.9 kB 9.6 MB/s eta 0:00:00
Downloading llama_index_core-0.12.28-py3-none-any.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 34.5 MB/s eta 0:00:00
Downloading python_dotenv-1.1.0-py3-none-any.whl (20 kB)
Downloading banks-2.1.1-py3-none-any.whl (28 kB)
Downloading dirtyjson-1.0.8-py3-none-any.whl (25 kB)
Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Downloading tiktoken-0.9.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 37.1 MB/s eta 0:00:00
Downloading typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Downloading dataclasses_json-0.6.7-py3-none-any.whl (28 kB)
Downloading marshmallow-3.26.1-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.9/50.9 kB 3.6 MB/s eta 0:00:00
Downloading mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)
Downloading griffe-1.7.2-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.2/129.2 kB 9.3 MB/s eta 0:00:00
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Installing collected packages: filetype, dirtyjson, python-dotenv, mypy-extensions, marshmallow, colorama, typing-inspect, tiktoken, griffe, llama-cloud, dataclasses-json, banks, llama-index-core, llama-cloud-services, llama-parse
Successfully installed banks-2.1.1 colorama-0.4.6 dataclasses-json-0.6.7 dirtyjson-1.0.8 filetype-1.2.0 griffe-1.7.2 llama-cloud-0.1.17 llama-cloud-services-0.6.9 llama-index-core-0.12.28 llama-parse-0.6.4.post1 marshmallow-3.26.1 mypy-extensions-1.0.0 python-dotenv-1.1.0 tiktoken-0.9.0 typing-inspect-0.9.0

In [ ]:
import nest_asyncio

nest_asyncio.apply()

In [ ]:
import os

os.environ["LLAMA_CLOUD_API_KEY"]="llx-HdgBKfPPO6vVO0CeuSkOduMH5DaCuLwuDsBHJsjMLS2Y6dod"

In [ ]:
from llama_parse import LlamaParse

In [ ]:
documents_with_instruction = LlamaParse(
    result_type="markdown",
    parsing_instruction="""
    This is the a school financial report. I would need you to extract information which are related to enrollment, headcount, FTE, admission, faculty, tuition and fees, student characteristics(Graduation rate, ACT, SAT scores etc.)
    tips: Sometimes Graduate could be written as GR or Grad or, some university has multiple graduate schools, such as school of business, college of liberal artsm or GR Non-degree. you should include these data as well.

    """
    ).load_data("/content/Mt St Mary's fall 24 continuing disclosure.pdf")

WARNING: parsing_instruction is deprecated. Use system_prompt, system_prompt_append or user_prompt instead.
Started parsing the file under job_id a9f9fdf7-b5da-4664-85d2-59b34b309fec
.

In [ ]:
print(documents_with_instruction[0].text[:2000])

does not contain

In [ ]:
import re
pattern = r"does not contain"

for i in range(len(documents_with_instruction)):
    if not re.search(pattern, documents_with_instruction[i].text[:1000]):
        # Process the document if it does NOT contain "does not contain"
        print("This is page ", i)
        print(documents_with_instruction[i].text[:100000])

This is page  1
It seems that the text you provided is not sufficient to extract the specific information related to enrollment, headcount, FTE, admission, faculty, tuition and fees, and student characteristics. Please provide more detailed content from the financial report, and I will be happy to help you extract the relevant information.
This is page  6
Based on the provided financial report for Mount St. Mary's University, here are the extracted details related to enrollment, headcount, FTE, admission, faculty, tuition and fees, and student characteristics:

### Tuition and Fees
- **Tuition and Fees (2024)**: $36,014,479
- **Tuition and Fees (2023)**: $35,027,666

### Room and Board
- **Room and Board (2024)**: $20,360,719
- **Room and Board (2023)**: $19,973,593

### Net Student Revenue
- **Net Student Revenue (2024)**: $56,375,198
- **Net Student Revenue (2023)**: $55,001,259

### Operating Expenses
- **Total Operating Expenses (2024)**: $86,698,756
- **Total Operating Expenses (2023)**: $83,334,026

### Change in Net Assets from Operations
- **Change in Net Assets from Operations (2024)**: $(4,496,164)
- **Change in Net Assets from Operations (2023)**: $333,144

### Non-Operating Revenue and Other Gains (Losses)
- **Total Non-Operating Revenue and Other Gains (2024)**: $11,447,917
- **Total Non-Operating Revenue and Other Gains (2023)**: $3,176,064

### Net Assets
- **Beginning Net Assets (2024)**: $123,534,852
- **Ending Net Assets (2024)**: $130,486,605
- **Beginning Net Assets (2023)**: $120,025,644

### Additional Information
- The report does not provide specific data on enrollment numbers, headcount, FTE, admission statistics, faculty details, or student characteristics such as graduation rates, ACT, or SAT scores.

If you have more specific sections of the report or additional pages, please provide them for further extraction of relevant data.
This is page  7
Based on the provided financial report for Mount St. Mary's University, here are the extracted details related to enrollment, headcount, FTE, admission, faculty, tuition and fees, and student characteristics:

### Tuition and Fees
- **Tuition and Fees Revenue**: $35,027,666
- **Room and Board Revenue**: $19,973,593
- **Net Student Revenue**: $55,001,259

### Enrollment and Headcount
- The report does not provide specific numbers for enrollment, headcount, or FTE (Full-Time Equivalent) students. Additional data would be needed to extract this information.

### Faculty
- The report does not include specific details regarding faculty numbers or characteristics. Additional data would be needed to extract this information.

### Student Characteristics
- The report does not provide specific metrics such as graduation rates, ACT, or SAT scores. Additional data would be needed to extract this information.

### Summary
The financial report primarily focuses on the operating revenue and expenses of the university, with specific figures for tuition and fees, room and board, and net student revenue. However, it lacks detailed information on enrollment, headcount, faculty, and student characteristics. Further documentation would be required to obtain a comprehensive view of these aspects.
This is page  9
Based on the provided financial report for Mount St. Mary's University, here are the extracted details related to enrollment, headcount, FTE, admission, faculty, tuition and fees, and student characteristics:

1. **Enrollment and Headcount:**
- The University provides academic programs to approximately **2,400 students**.

2. **Graduate Programs:**
- The report mentions both undergraduate and graduate programs, indicating that the University offers graduate education, although specific numbers for graduate enrollment are not provided.

3. **Student Characteristics:**
- There are no specific details provided regarding graduation rates, ACT, or SAT scores in the text provided.

4. **Tuition and Fees:**
- The report does not include specific information regarding tuition and fees.

5. **Faculty:**
- The report does not provide any information regarding faculty numbers or characteristics.

6. **Admission:**
- There is no specific information regarding admission processes or statistics.

Overall, the report provides limited quantitative data on enrollment and does not include detailed information on other requested categories such as graduation rates, standardized test scores, tuition and fees, faculty, or admission statistics.
This is page  31
Here is the extracted information related to enrollment, headcount, FTE, admission, faculty, tuition and fees, and student characteristics from the financial report of Mount St. Mary's University:

### Enrollment and Headcount
- **Undergraduate Enrollment (2024)**: $25,521,495 (net of scholarships)
- **Graduate Enrollment (2024)**: $6,247,704 (net of scholarships)
- **Seminary Enrollment (2024)**: $4,245,280 (net of scholarships)

### Tuition and Fees
- **Total Tuition and Fees (2024)**: $36,014,479 (net of scholarships)
- **Undergraduate Tuition and Fees (2023)**: $25,687,315 (net of scholarships)
- **Graduate Tuition and Fees (2023)**: $5,447,720 (net of scholarships)
- **Seminary Tuition and Fees (2023)**: $3,892,631 (net of scholarships)
- **Total Tuition and Fees (2023)**: $35,027,666 (net of scholarships)

### Student Financial Aid
- **Student Financial Aid**: Reflected as contra-tuition revenue in the consolidated statements of activities.

### Additional Notes
- The report mentions that tuition revenue and discounts are billed and collected prior to the end of each semester, and revenues are recognized over the course of each semester as educational services are delivered.
- The amount of deferred revenue for summer terms is considered immaterial to the financial statements.

### Student Characteristics
- The report does not provide specific data on graduation rates, ACT, or SAT scores.

### Summary
The financial report provides a detailed breakdown of tuition and fees for different student categories (undergraduate, graduate, and seminary) for the years 2024 and 2023, along with information on student financial aid. However, it lacks specific data on student characteristics such as graduation rates and standardized test scores.
This is page  40
It appears that the text provided is not clear or coherent enough to extract specific information related to enrollment, headcount, FTE, admission, faculty, tuition and fees, or student characteristics. The text seems to be a mix of numbers and letters without any structured data.

If you have a more structured document or specific sections of the financial report that contain the relevant information, please provide that, and I would be happy to help extract the necessary details.
This is page  43
The provided text appears to be a scanned document with OCR (Optical Character Recognition) errors, making it difficult to extract coherent information. However, based on the request for specific data points related to enrollment, headcount, FTE, admission, faculty, tuition and fees, and student characteristics, I will outline the types of information typically included in a school financial report for these categories:

1. **Enrollment and Headcount**:
- Total number of enrolled students (undergraduate and graduate).
- Breakdown of enrollment by program (e.g., School of Business, College of Liberal Arts).
- Full-Time Equivalent (FTE) students.

2. **Admission**:
- Number of applications received.
- Acceptance rate.
- Enrollment yield (percentage of accepted students who enroll).

3. **Faculty**:
- Total number of faculty members.
- Breakdown of faculty by full-time and part-time status.
- Faculty-to-student ratio.

4. **Tuition and Fees**:
- Tuition rates for undergraduate and graduate programs.
- Additional fees (e.g., technology fees, activity fees).

5. **Student Characteristics**:
- Graduation rate (percentage of students who graduate within a specific time frame).
- Average ACT and SAT scores of incoming students.
- Demographic information (e.g., percentage of students receiving financial aid, diversity statistics).

If you have a clearer or more specific section of the report, I can assist in extracting the relevant data more accurately.
This is page  44
Here is the extracted information related to enrollment, headcount, FTE, admission, faculty, tuition and fees, and student characteristics from the provided financial report:

### Admissions and Enrollment
- **First Year Students Applications, Acceptances, and Enrollments:**
- **Fall 2024:**
- Applications: 6,041
- Acceptances: 4,459
- Matriculates: 545
- % Enrolled: 73.8%
- **Fall 2023:**
- Applications: 5,437
- Acceptances: 3,896
- Matriculates: 482
- % Enrolled: 71.7%
- **Fall 2022:**
- Applications: 4,346
- Acceptances: 3,458
- Matriculates: 459
- % Enrolled: 79.6%
- **Fall 2021:**
- Applications: 4,620
- Acceptances: 3,777
- Matriculates: 532
- % Enrolled: 81.8%
- **Fall 2020:**
- Applications: 6,442
- Acceptances: 5,221
- Matriculates: 647
- % Enrolled: 81.0%

### Student Quality
- **Average SAT and ACT Scores for Entering First Year Students:**
- **Fall 2024:**
- SAT (Mean Total): 1162
- ACT (Average): 22.7
- **Fall 2023:**
- SAT (Mean Total): 1142
- ACT (Average): 23.2
- **Fall 2022:**
- SAT (Mean Total): 1155
- ACT (Average): 23.2
- **Fall 2021:**
- SAT (Mean Total): 1141
- ACT (Average): 23.5
- **Fall 2020:**
- SAT (Mean Total): 1085
- ACT (Average): 22.1

### Additional Notes
- The university adopted a test score optional policy starting with the Fall 2020 admissions cycle.

This information provides a comprehensive overview of the admissions and enrollment statistics, as well as student quality metrics for Mount Saint Mary's University.
This is page  45
Here is the extracted information related to enrollment, headcount, FTE, admission, faculty, tuition and fees, and student characteristics from the provided financial report:

### Enrollment and Headcount
- **Undergraduate Enrollment:**
- 2024: 1830 (Total FT: 1735)
- 2023: 1873 (Total FT: 1774)
- 2022: 1896 (Total FT: 1815)
- 2021: 2055 (Total FT: 1965)
- 2020: 2072 (Total FT: 1983)

- **Graduate Enrollment:**
- GR College of Business:
- 2024: 188
- 2023: 182
- 2022: 179
- 2021: 172
- 2020: 176
- GR College of Education:
- 2024: 127
- 2023: 139
- 2022: 140
- 2021: 123
- 2020: 130
- GR Seminary:
- 2024: 146
- 2023: 157
- 2022: 112
- 2021: 101
- 2020: 100
- GR College of Liberal Arts:
- 2024: 71
- 2023: 93
- 2022: 68
- 2021: 61
- 2020: 66
- GR College of Health:
- 2024: 133
- 2023: 177
- 2022: 163
- 2021: 168
- 2020: 173
- GR College of Mathematics:
- 2024: 133
- 2023: 177
- 2022: 162
- 2021: 168
- 2020: 172
- GR Non-degree:
- 2024: 6
- 2023: 3
- 2022: 1
- 2021: 3
- 2020: 3

### Full-Time Equivalent (FTE)
- **Calculation Method:**
- Undergraduate: FT Headcount + PT Credit Hrs/15
- Graduate and Seminary: FT Headcount + PT Credit Hrs/9

- **Total FTE:**
- 2024: 2408
- 2023: 2499
- 2022: 2456
- 2021: 2570
- 2020: 2561

### Retention and Graduation Rates
- **Retention Rates:**
- 2024: 77%
- 2023: 75%
- 2022: 79%
- 2021: 74%
- 2020: 76%

- **Graduation Rates:**
- 4-Year Graduates:
- 2024: 36%
- 2023: 56%
- 2022: 64%
- 2021: 49%
- 2020: 60%
- 5-Year Graduates:
- 2024: 64%
- 2023: 56%
- 2022: 62%
- 2021: 56%
- 2020: 64%

### Student Characteristics
- **First Year Fresh/Soph Retention:**
- 2027: 71%
- 2026: 71%
- 2025: 68%
- 2024: 77%
- 2023: 75%
- 2022: 79%
- 2021: 74%
- 2020: 76%

This summary includes the relevant data points related to enrollment, headcount, FTE, admission, faculty, tuition and fees, and student characteristics as requested.
This is page  46
Here is the extracted information related to enrollment, headcount, FTE, admission, faculty, tuition and fees, and student characteristics from the provided financial report:

### Tuition and Fees
- **2024-2025**:
- Tuition: $48,630
- Fees: $2,650
- Room: $7,400
- Board: $610
- Credit (per credit): $610
- Additional Fees (per credit): $710
- **2023-2024**:
- Tuition: $47,240
- Fees: $2,500
- Room: $7,250
- Board: $600
- Credit (per credit): $600
- Additional Fees (per credit): $700
- **2022-2023**:
- Tuition: $45,870
- Fees: $7,290
- Room: $7,030
- Board: $594
- Credit (per credit): $594
- Additional Fees (per credit): $694
- **2021-2022**:
- Tuition: $44,750
- Fees: $7,110
- Room: $6,850
- Board: $585
- Credit (per credit): $585
- Additional Fees (per credit): $685
- **2020-2021**:
- Tuition: $43,650
- Fees: $6,940
- Room: $6,690
- Board: $540
- Credit (per credit): $585
- Additional Fees (per credit): $650
- **2019-2020**:
- Tuition: $42,590
- Fees: $6,780
- Room: $6,550
- Board: $530
- Credit (per credit): $565
- Additional Fees (per credit): $670

### Liquidity and Financial Information
- **Cash Balance** (as of June 30):
- 2020: $22,147,838
- 2021: $23,698,608
- 2022: $23,400,302
- 2023: $29,203,790
- 2024: $28,489,534

### Operating Expenses
- **Operating Expenses** (as of June 30):
- 2020: $69,224,297
- 2021: $72,053,250
- 2022: $79,550,960
- 2023: $83,334,026
- 2024: $86,698,756

### Daily Expenses
- **Daily Expenses**:
- 2020: $171,225
- 2021: $178,396
- 2022: $198,317
- 2023: $208,440
- 2024: $217,278

### Days Liquidity
- **Days Liquidity**:
- 2020: 151 days
- 2021: 163 days
- 2022: 127 days
- 2023: 188 days
- 2024: 144 days

### Additional Notes
- The report does not provide specific data on enrollment, headcount, FTE, admission, faculty, or student characteristics such as graduation rates, ACT, or SAT scores. If this information is available in other sections of the report, please provide that text for further extraction.

In [ ]:
extracted_tables = []  # To store the filtered documents

for document in documents_with_instruction:
    text = document.text
    if re.search(r"It seems that the text provided is not", text):
        continue
    if re.search(r"does not contain", text):
        continue

    # Check if the document is relevant:
    if text.lstrip().startswith("Here is the extracted information") or re.search(r"^\d{4}\s+", text, re.MULTILINE):
        extracted_tables.append(document)

# For verification, print out the first part of each filtered document
for i, doc in enumerate(extracted_tables):
    print(doc.text[:12000])

Here is the extracted information related to enrollment, headcount, FTE, admission, faculty, tuition and fees, and student characteristics from the financial report of Mount St. Mary's University:

### Enrollment and Headcount
- **Undergraduate Enrollment (2024)**: $25,521,495 (net of scholarships)
- **Graduate Enrollment (2024)**: $6,247,704 (net of scholarships)
- **Seminary Enrollment (2024)**: $4,245,280 (net of scholarships)

### Tuition and Fees
- **Total Tuition and Fees (2024)**: $36,014,479 (net of scholarships)
- **Undergraduate Tuition and Fees (2023)**: $25,687,315 (net of scholarships)
- **Graduate Tuition and Fees (2023)**: $5,447,720 (net of scholarships)
- **Seminary Tuition and Fees (2023)**: $3,892,631 (net of scholarships)
- **Total Tuition and Fees (2023)**: $35,027,666 (net of scholarships)

### Student Financial Aid
- **Student Financial Aid**: Reflected as contra-tuition revenue in the consolidated statements of activities.

### Additional Notes
- The report mentions that tuition revenue and discounts are billed and collected prior to the end of each semester, and revenues are recognized over the course of each semester as educational services are delivered.
- The amount of deferred revenue for summer terms is considered immaterial to the financial statements.

### Student Characteristics
- The report does not provide specific data on graduation rates, ACT, or SAT scores.

### Summary
The financial report provides a detailed breakdown of tuition and fees for different student categories (undergraduate, graduate, and seminary) for the years 2024 and 2023, along with information on student financial aid. However, it lacks specific data on student characteristics such as graduation rates and standardized test scores.
Here is the extracted information related to enrollment, headcount, FTE, admission, faculty, tuition and fees, and student characteristics from the provided financial report:

### Admissions and Enrollment
- **First Year Students Applications, Acceptances, and Enrollments:**
- **Fall 2024:**
- Applications: 6,041
- Acceptances: 4,459
- Matriculates: 545
- % Enrolled: 73.8%
- **Fall 2023:**
- Applications: 5,437
- Acceptances: 3,896
- Matriculates: 482
- % Enrolled: 71.7%
- **Fall 2022:**
- Applications: 4,346
- Acceptances: 3,458
- Matriculates: 459
- % Enrolled: 79.6%
- **Fall 2021:**
- Applications: 4,620
- Acceptances: 3,777
- Matriculates: 532
- % Enrolled: 81.8%
- **Fall 2020:**
- Applications: 6,442
- Acceptances: 5,221
- Matriculates: 647
- % Enrolled: 81.0%

### Student Quality
- **Average SAT and ACT Scores for Entering First Year Students:**
- **Fall 2024:**
- SAT (Mean Total): 1162
- ACT (Average): 22.7
- **Fall 2023:**
- SAT (Mean Total): 1142
- ACT (Average): 23.2
- **Fall 2022:**
- SAT (Mean Total): 1155
- ACT (Average): 23.2
- **Fall 2021:**
- SAT (Mean Total): 1141
- ACT (Average): 23.5
- **Fall 2020:**
- SAT (Mean Total): 1085
- ACT (Average): 22.1

### Additional Notes
- The university adopted a test score optional policy starting with the Fall 2020 admissions cycle.

This information provides a comprehensive overview of the admissions and enrollment statistics, as well as student quality metrics for Mount Saint Mary's University.
Here is the extracted information related to enrollment, headcount, FTE, admission, faculty, tuition and fees, and student characteristics from the provided financial report:

### Enrollment and Headcount
- **Undergraduate Enrollment:**
- 2024: 1830 (Total FT: 1735)
- 2023: 1873 (Total FT: 1774)
- 2022: 1896 (Total FT: 1815)
- 2021: 2055 (Total FT: 1965)
- 2020: 2072 (Total FT: 1983)

- **Graduate Enrollment:**
- GR College of Business:
- 2024: 188
- 2023: 182
- 2022: 179
- 2021: 172
- 2020: 176
- GR College of Education:
- 2024: 127
- 2023: 139
- 2022: 140
- 2021: 123
- 2020: 130
- GR Seminary:
- 2024: 146
- 2023: 157
- 2022: 112
- 2021: 101
- 2020: 100
- GR College of Liberal Arts:
- 2024: 71
- 2023: 93
- 2022: 68
- 2021: 61
- 2020: 66
- GR College of Health:
- 2024: 133
- 2023: 177
- 2022: 163
- 2021: 168
- 2020: 173
- GR College of Mathematics:
- 2024: 133
- 2023: 177
- 2022: 162
- 2021: 168
- 2020: 172
- GR Non-degree:
- 2024: 6
- 2023: 3
- 2022: 1
- 2021: 3
- 2020: 3

### Full-Time Equivalent (FTE)
- **Calculation Method:**
- Undergraduate: FT Headcount + PT Credit Hrs/15
- Graduate and Seminary: FT Headcount + PT Credit Hrs/9

- **Total FTE:**
- 2024: 2408
- 2023: 2499
- 2022: 2456
- 2021: 2570
- 2020: 2561

### Retention and Graduation Rates
- **Retention Rates:**
- 2024: 77%
- 2023: 75%
- 2022: 79%
- 2021: 74%
- 2020: 76%

- **Graduation Rates:**
- 4-Year Graduates:
- 2024: 36%
- 2023: 56%
- 2022: 64%
- 2021: 49%
- 2020: 60%
- 5-Year Graduates:
- 2024: 64%
- 2023: 56%
- 2022: 62%
- 2021: 56%
- 2020: 64%

### Student Characteristics
- **First Year Fresh/Soph Retention:**
- 2027: 71%
- 2026: 71%
- 2025: 68%
- 2024: 77%
- 2023: 75%
- 2022: 79%
- 2021: 74%
- 2020: 76%

This summary includes the relevant data points related to enrollment, headcount, FTE, admission, faculty, tuition and fees, and student characteristics as requested.
Here is the extracted information related to enrollment, headcount, FTE, admission, faculty, tuition and fees, and student characteristics from the provided financial report:

### Tuition and Fees
- **2024-2025**:
- Tuition: $48,630
- Fees: $2,650
- Room: $7,400
- Board: $610
- Credit (per credit): $610
- Additional Fees (per credit): $710
- **2023-2024**:
- Tuition: $47,240
- Fees: $2,500
- Room: $7,250
- Board: $600
- Credit (per credit): $600
- Additional Fees (per credit): $700
- **2022-2023**:
- Tuition: $45,870
- Fees: $7,290
- Room: $7,030
- Board: $594
- Credit (per credit): $594
- Additional Fees (per credit): $694
- **2021-2022**:
- Tuition: $44,750
- Fees: $7,110
- Room: $6,850
- Board: $585
- Credit (per credit): $585
- Additional Fees (per credit): $685
- **2020-2021**:
- Tuition: $43,650
- Fees: $6,940
- Room: $6,690
- Board: $540
- Credit (per credit): $585
- Additional Fees (per credit): $650
- **2019-2020**:
- Tuition: $42,590
- Fees: $6,780
- Room: $6,550
- Board: $530
- Credit (per credit): $565
- Additional Fees (per credit): $670

### Liquidity and Financial Information
- **Cash Balance** (as of June 30):
- 2020: $22,147,838
- 2021: $23,698,608
- 2022: $23,400,302
- 2023: $29,203,790
- 2024: $28,489,534

### Operating Expenses
- **Operating Expenses** (as of June 30):
- 2020: $69,224,297
- 2021: $72,053,250
- 2022: $79,550,960
- 2023: $83,334,026
- 2024: $86,698,756

### Daily Expenses
- **Daily Expenses**:
- 2020: $171,225
- 2021: $178,396
- 2022: $198,317
- 2023: $208,440
- 2024: $217,278

### Days Liquidity
- **Days Liquidity**:
- 2020: 151 days
- 2021: 163 days
- 2022: 127 days
- 2023: 188 days
- 2024: 144 days

### Additional Notes
- The report does not provide specific data on enrollment, headcount, FTE, admission, faculty, or student characteristics such as graduation rates, ACT, or SAT scores. If this information is available in other sections of the report, please provide that text for further extraction.

# Data Handling and Organisation using Openai

In [ ]:
!pip install openai

Requirement already satisfied: openai in /usr/local/lib/python3.11/dist-packages (1.70.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.11/dist-packages (from openai) (4.9.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from openai) (0.9.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.11/dist-packages (from openai) (2.11.1)
Requirement already satisfied: sniffio in /usr/local/lib/python3.11/dist-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.11/dist-packages (from openai) (4.67.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.11/dist-packages (from openai) (4.13.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.11/dist-packages (from anyio<5,>=3.5.0->openai) (3.10)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->openai) (2025.1.31)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.7)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.14.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.9.0->openai) (2.33.0)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.9.0->openai) (0.4.0)

In [ ]:
from openai import OpenAI
from getpass import getpass
client = OpenAI(api_key=getpass("Enter your OpenAI API key: "))

Enter your OpenAI API key: ··········

In [ ]:
models = client.models.list()
for model in models.data:
    print(model.id)

dall-e-3
dall-e-2
gpt-4o-audio-preview-2024-10-01
gpt-4o-transcribe
gpt-4o-mini-transcribe
babbage-002
gpt-4o-mini-tts
tts-1-hd-1106
text-embedding-3-large
text-embedding-ada-002
omni-moderation-latest
tts-1-hd
gpt-4o-mini-audio-preview
gpt-4o-audio-preview
o1-preview-2024-09-12
gpt-3.5-turbo-instruct-0914
gpt-4o-mini-search-preview
tts-1-1106
davinci-002
gpt-3.5-turbo-1106
gpt-3.5-turbo-instruct
gpt-3.5-turbo
gpt-4o-mini-search-preview-2025-03-11
gpt-4o-2024-11-20
whisper-1
gpt-3.5-turbo-0125
gpt-4o-2024-05-13
gpt-3.5-turbo-16k
o1-preview
gpt-4o-search-preview
gpt-4.5-preview
gpt-4.5-preview-2025-02-27
gpt-4o-search-preview-2025-03-11
tts-1
omni-moderation-2024-09-26
text-embedding-3-small
gpt-4o
gpt-4o-mini
gpt-4o-2024-08-06
gpt-4o-mini-2024-07-18
o1-mini
gpt-4o-mini-audio-preview-2024-12-17
o1-mini-2024-09-12

In [ ]:
openai.api_key = "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"

In [ ]:
response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Which university has the best MFE program?"}
    ],
    temperature=0.2
)
print(response.choices[0].message.content)

The capital of France is Paris.

In [ ]:
base_prompt = """
You are a data transformation assistant specializing in financial and educational data. I will provide you with multiple pieces of extracted text from different sections of Mount Saint Mary's University’s financial report. Your task is to consolidate all this information into a single summary formatted as a JSON object that represents a table.

The table must have columns for the years: 2024, 2023, 2022, 2021, and 2020. Each row in the table should correspond to a specific metric with its value for each year.

Important instructions:
1. Units & Data Types:
   - If a value contains a "$" symbol, treat it as financial data and preserve its formatting exactly (e.g. "$25,521,495" with the dollar sign and comma separators). Financial values are typically large (often in the millions).
   - If a value includes a "%" symbol, treat it as a percentage.
   - Values without a currency or percentage symbol are assumed to be headcounts, test scores, or similar numbers. Ensure that headcount values are realistic (typically within the range 0–50,000). If you see a very large number without a "$", it is likely incorrect for headcount.
2. Data Cleaning:
   - Remove any extra notes or text inside parentheses.
   - If a metric is provided in multiple parts (for example, Graduate Enrollment broken down by college), sum the parts to yield one total value.
3. Formatting Requirements:
   - The output must be exactly valid JSON without any markdown formatting, code block markers, or extra commentary.
   - Do not include any additional explanation or text.
   - If a particular value is missing for a metric, leave it as an empty string.
4. Metrics to Include:
   Please include the following metrics in the final JSON output:
   - Undergraduate Enrollment (Headcount)
   - Graduate Enrollment (Total)
   - Total FTE Students
   - First Year Students Applications
   - First Year Students Acceptances
   - First Year Students Matriculates
   - % Enrolled (for first year students)
   - Average SAT Score (Freshman)
   - Average ACT Score (Freshman)
   - Retention Rate %
   - Graduation Rate (within 4 yrs) %
   - Graduation Rate (within 5 yrs) %
   - Tuition (for the appropriate academic year; use the starting year)
   - Room & Board (if available; include as separate values or combined as appropriate)
   - Cash Balance (as of June 30)
   - Operating Expenses (as of June 30)
   - Daily Expenses
   - Days Liquidity

The final JSON output must follow this exact structure:

{
  "Metric Name": {
    "2024": "value",
    "2023": "value",
    "2022": "value",
    "2021": "value",
    "2020": "value"
  },
  ... (other metrics) ...
}

Now, here is the extracted information from the report:
[INSERT EXTRACTED TEXT HERE]
"""

In [ ]:
structured_outputs = []

for i, doc in enumerate(extracted_tables):
    print(f"Processing document {i + 1}...")

    user_prompt = base_prompt + "\n\n" + doc.text[:16000]  # truncate if too large

    response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "system", "content": "You are a financial data parser and formatter."},
        {"role": "user", "content": user_prompt}
    ],
    temperature=0.2
)


    content = response.choices[0].message.content
    structured_outputs.append(content)

Processing document 1...
Processing document 2...
Processing document 3...
Processing document 4...

In [ ]:
import json
import re
import pandas as pd

def strip_code_block(text):
    """
    Remove markdown code block markers (e.g. ```json ... ```) from the text.
    If multiple parts exist, return the content in the first code block.
    """
    parts = text.split("```")
    if len(parts) >= 3:
        # The JSON content is usually in the second element
        return parts[1].strip()
    else:
        return text.strip()

dfs = []

for i, result in enumerate(structured_outputs):
    raw_text = result  # result is the raw GPT output (a string)

    # Strip the markdown formatting
    cleaned_text = strip_code_block(raw_text)

    try:
        data = json.loads(cleaned_text)
        df = pd.DataFrame.from_dict(data, orient='index')
        df.index.name = "Metric"
        dfs.append(df)
    except Exception as e:
        # Optionally save the raw text for further debugging
        with open(f"failed_document_{i+1}.txt", "w") as f:
            f.write(raw_text)

# Optionally, visualize the first DataFrame if any were successfully parsed
if dfs:
    display(dfs[0])
else:
    print("No documents were successfully processed.")

                                             2024         2023 2022 2021 2020
Metric
Undergraduate Enrollment (Headcount)  $25,521,495
Graduate Enrollment (Total)            $6,247,704   $5,447,720
Total FTE Students
First Year Students Applications
First Year Students Acceptances
First Year Students Matriculates
% Enrolled (for first year students)
Average SAT Score (Freshman)
Average ACT Score (Freshman)
Retention Rate %
Graduation Rate (within 4 yrs) %
Graduation Rate (within 5 yrs) %
Tuition                               $36,014,479  $35,027,666
Room & Board
Cash Balance (as of June 30)
Operating Expenses (as of June 30)
Daily Expenses
Days Liquidity

In [ ]:
from IPython.display import display

for idx, df in enumerate(dfs, start=1):
    print(f"DataFrame for Document {idx}:")
    display(df)
    print("\n" + "="*80 + "\n")

DataFrame for Document 1:

                                             2024         2023 2022 2021 2020
Metric
Undergraduate Enrollment (Headcount)  $25,521,495
Graduate Enrollment (Total)            $6,247,704   $5,447,720
Total FTE Students
First Year Students Applications
First Year Students Acceptances
First Year Students Matriculates
% Enrolled (for first year students)
Average SAT Score (Freshman)
Average ACT Score (Freshman)
Retention Rate %
Graduation Rate (within 4 yrs) %
Graduation Rate (within 5 yrs) %
Tuition                               $36,014,479  $35,027,666
Room & Board
Cash Balance (as of June 30)
Operating Expenses (as of June 30)
Daily Expenses
Days Liquidity

================================================================================

DataFrame for Document 2:

                                       2024   2023   2022   2021   2020
Metric
Undergraduate Enrollment (Headcount)
Graduate Enrollment (Total)
Total FTE Students
First Year Students Applications      6,041  5,437  4,346  4,620  6,442
First Year Students Acceptances       4,459  3,896  3,458  3,777  5,221
First Year Students Matriculates        545    482    459    532    647
% Enrolled (for first year students)  73.8%  71.7%  79.6%  81.8%  81.0%
Average SAT Score (Freshman)           1162   1142   1155   1141   1085
Average ACT Score (Freshman)           22.7   23.2   23.2   23.5   22.1
Retention Rate %
Graduation Rate (within 4 yrs) %
Graduation Rate (within 5 yrs) %
Tuition
Room & Board
Cash Balance (as of June 30)
Operating Expenses (as of June 30)
Daily Expenses
Days Liquidity

================================================================================

DataFrame for Document 3:

                                      2024  2023  2022  2021  2020
Metric
Undergraduate Enrollment (Headcount)  1830  1873  1896  2055  2072
Graduate Enrollment (Total)            784   751   675   625   644
Total FTE Students                    2408  2499  2456  2570  2561
First Year Students Applications
First Year Students Acceptances
First Year Students Matriculates
% Enrolled (for first year students)
Average SAT Score (Freshman)
Average ACT Score (Freshman)
Retention Rate %                       77%   75%   79%   74%   76%
Graduation Rate (within 4 yrs) %       36%   56%   64%   49%   60%
Graduation Rate (within 5 yrs) %       64%   56%   62%   56%   64%
Tuition
Room & Board
Cash Balance (as of June 30)
Operating Expenses (as of June 30)
Daily Expenses
Days Liquidity

================================================================================

DataFrame for Document 4:

,2024,2023,2022,2021,2020
Metric,,,,,
Undergraduate Enrollment (Headcount),,,,,
Graduate Enrollment (Total),,,,,
Total FTE Students,,,,,
First Year Students Applications,,,,,
First Year Students Acceptances,,,,,
First Year Students Matriculates,,,,,
% Enrolled (for first year students),,,,,
Average SAT Score (Freshman),,,,,
Average ACT Score (Freshman),,,,,
Retention Rate %,,,,,
Graduation Rate (within 4 yrs) %,,,,,
Graduation Rate (within 5 yrs) %,,,,,
Tuition,"$48,630","$47,240","$45,870","$44,750","$43,650"
Room & Board,"$8,010","$7,850","$7,624","$7,435","$7,230"
Cash Balance (as of June 30),"$28,489,534","$29,203,790","$23,400,302","$23,698,608","$22,147,838"
Operating Expenses (as of June 30),"$86,698,756","$83,334,026","$79,550,960","$72,053,250","$69,224,297"
Daily Expenses,"$217,278","$208,440","$198,317","$178,396","$171,225"
Days Liquidity,144 days,188 days,127 days,163 days,151 days

================================================================================

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------